# Generated by Django 5.1.4 on 2024-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bron',
            options={'verbose_name': 'Bron qilingan stol', 'verbose_name_plural': 'Bron qilingan stollar'},
        ),
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'Povar malumotlari', 'verbose_name_plural': 'Povar malumotlari'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Mijoz izohi', 'verbose_name_plural': 'Mijozlar izohlari'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Kontakt malumot', 'verbose_name_plural': 'Kontakt malumotlari'},
        ),
        migrations.AlterModelOptions(
            name='ishvaqti',
            options={'verbose_name': 'Ish Vaqti', 'verbose_name_plural': 'Ish Vaqti'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='tavsiyataom',
            options={'verbose_name': 'Tavsiya qilingan Taom', 'verbose_name_plural': 'Tavsiya qilingan Taomlar'},
        ),
        migrations.RemoveField(
            model_name='bron',
            name='email',
        ),
        migrations.AddField(
            model_name='bron',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
