# Generated by Django 5.1.4 on 2024-12-23 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bron_options_alter_chefs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.EmailField(default=1, max_length=254, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aqtiv yoki NeAqtiv'),
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='description',
            field=models.TextField(verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Foiz'),
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='end_date',
            field=models.DateTimeField(verbose_name='tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlash vaqti'),
        ),
        migrations.AlterField(
            model_name='aksiya',
            name='title',
            field=models.CharField(max_length=255, verbose_name='sarlavha'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='datetime',
            field=models.DateTimeField(verbose_name='Bron kuni'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='number_of_people',
            field=models.PositiveIntegerField(verbose_name='Qancha odam kelishi'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Mijoz telefor raqami'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='special_request',
            field=models.TextField(blank=True, null=True, verbose_name='Qoshimcha takliflari mijozlarni'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Darajasi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Oshpazning rasmi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Oshpaz ismi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='feedback',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='ishvaqti',
            name='day',
            field=models.CharField(max_length=50, verbose_name='Kun'),
        ),
        migrations.AlterField(
            model_name='ishvaqti',
            name='end_time',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='ishvaqti',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlash vaqti'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategorya nomi'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.menucategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Qoshimcha malumot'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='tavsiyataom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='tavsifi'),
        ),
        migrations.AlterField(
            model_name='tavsiyataom',
            name='end_date',
            field=models.DateField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='tavsiyataom',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='main.menuitem', verbose_name='Tavsiya qilinadigan taom'),
        ),
        migrations.AlterField(
            model_name='tavsiyataom',
            name='start_date',
            field=models.DateField(verbose_name='Boshlash vaqti'),
        ),
    ]
